-- ASSIGNMENT ON CO-RELATED SUBQUERY


-- 1. WAQTD NAME AND SALARY WHO IS EARNING 5TH MAXIMUM SALARY.

SELECT E1.ENAME,E1.SAL
FROM EMP E1
WHERE 5-1 IN (SELECT COUNT(DISTINCT E2.SAL)
              FROM EMP E2
              WHERE E1.SAL<E2.SAL);



-- 2. WAQTD DETAILS OF THE EMP WHO IS EARING 4TH MINIMUM SALARY.

SELECT *
FROM EMP E1
WHERE 4-1 IN (SELECT COUNT(DISTINCT E2.SAL)
              FROM EMP E2
              WHERE E1.SAL>E2.SAL);



-- 3. WAQTD DETAILS OF THE EMP WHO ARE EARNING TOP 5 MINIMUM SALARIES.

SELECT *
FROM EMP E1
WHERE 5 > (SELECT COUNT(DISTINCT E2.SAL)
           FROM EMP E2
           WHERE E1.SAL>E2.SAL);



-- 4. WAQTD NAME AND SALARY OF THE EMP WHO ARE EARNING TOP 3 MINIMUM & TOP 3 MAXIMUM SALARIES.

SELECT E1.ENAME,E1.SAL
FROM EMP E1
WHERE 3 > (SELECT COUNT(DISTINCT E2.SAL)
           FROM EMP E2
           WHERE E1.SAL>E2.SAL)
OR
3 > (SELECT COUNT(DISTINCT E2.SAL)
     FROM EMP E2
     WHERE E1.SAL<E2.SAL);



-- 5. WAQTD 1ST , 2ND ,4TH , 6TH,7TH, MAXIMUM SALARIES.

SELECT DISTINCT E1.SAL
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL)
       FROM EMP E2
       WHERE E1.SAL<E2.SAL) IN (0,1,3,5,6);



-- 6. WAQTD THE SALARY OF EMP WHO ARE EARNING TOP 3 MAXIMUM SALARIES.

SELECT DISTINCT E1.SAL
FROM EMP E1
WHERE 3 > (SELECT COUNT(DISTINCT E2.SAL)
           FROM EMP E2
           WHERE E1.SAL<E2.SAL);



-- 7. WAQTD 2,6 MAXIMUM SALARIES AND 8,4 MINIMUM SALARIES.

SELECT DISTINCT E1.SAL
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL)
       FROM EMP E2
       WHERE E1.SAL<E2.SAL) IN (1,5)
OR
(SELECT COUNT(DISTINCT E2.SAL)
 FROM EMP E2
 WHERE E1.SAL>E2.SAL) IN (7,3);



-- 8. WAQTD 16TH MAXIMUM SALARY.

SELECT E1.SAL
FROM EMP E1
WHERE 16-1 IN (SELECT COUNT(DISTINCT E2.SAL)
               FROM EMP E2
               WHERE E1.SAL<E2.SAL);



-- 9. WAQTD FIRST MAXIMUM SALARY AND FIRST MINIMUM SALARY.

SELECT E1.SAL
FROM EMP E1
WHERE 1-1 IN (SELECT COUNT(DISTINCT E2.SAL)
              FROM EMP E2
              WHERE E1.SAL<E2.SAL)
OR
1-1 IN (SELECT COUNT(DISTINCT E2.SAL)
        FROM EMP E2
        WHERE E1.SAL>E2.SAL);