--WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY. 
 SELECT ENAME,SAL*12 AS ANNUAL_SAL
 FROM EMP;
--WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE ALONG WITH HALF TERM SALARY.
 SELECT ENAME,JOB SAL/2 AS “HALF TERM SAL”
 FROM EMP;
--WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH AN ANNUALBONUS OF 2000. 
 SELECT EMP.*,SAL*12+2000 AS ANNUAL_SAL_WITH_BOUNUS
 FROM EMP;
--WAQTD NAME SALARY AND SALARY WITH A HIKE OF 10%. 
 SELECT ENAME,SAL,SAL+SAL*10/100 AS SAL_WITH_HIKE_10PER
 FROM EMP;
--WAQTD NAME AND SALARY WITH DEDUCTION OF 25%. 
 SELECT ENAME,SAL-SAL*25/100 AS “DEDUCTION_OF_25PER”
 FROM EMP;
--WAQTD NAME AND SALARY WITH MONTHLY HIKE OF 50. 
 SELECT ENAME,SAL+50 AS MONTHLY_HIKE_OF_50
 FROM EMP;
--WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10%. 
 SELECT ENAME,SAL*12-SAL*12*10/100 AS        ANNUANL_SAL_WITH_DEDUCTION
 FROM EMP;
--WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COMM). 
 SELECT ENAME,SAL+COMM AS TOTAL_SAL
 FROM EMP;
--WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY. 
 SELECT EMP.*,SAL*12 AS ANNUAL_SAL
 FROM EMP;
--WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY
  SELECT ENAME,JOB , SAL-100 AS PENELTY_IN_SAL
  FROM EMP;
