-- ASSIGNMENT ON INNER JOIN


-- 1. NAME OF THE EMPLOYEE AND HIS LOCATION OF ALL THE EMPLOYEES.
SELECT ENAME,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;


-- 2. WAQTD DNAME AND SALARY FOR ALL THE EMPLOYEE WORKING IN ACCOUNTING.
SELECT DNAME, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME='ACCOUNTING';


-- 3. WAQTD DNAME AND ANNUAL SALARY FOR ALL EMPLOYEES WHOS SALARY IS MORE THAN 2340.
SELECT DNAME,SAL*12 AS ANNUAL_SAL
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL>2340;


-- 4. WAQTD ENAME AND DNAME FOR EMPLOYEES HAVING CAHARACTER 'A' IN THEIR DNAME
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO =DEPT.DEPTNO
WHERE DNAME LIKE '%A%';


-- 5. WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES WORKING AS SALESMAN.
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON DEPT.DEPTNO = EMP.DEPTNO
WHERE JOB='SALESMAN';


-- 6. WADTD DNAME AND JOB FOR ALL THE EMPLOYEES WHOS JOB AND DNAME STARTS WITH CHARACTER 'S'.
SELECT DNAME, JOB
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB LIKE 'S%' AND DNAME LIKE 'S%';


-- 7. WAQTD DNAME AND MGR NO FOR EMPLOYEES REPORTING TO 7839.
SELECT DNAME,MGR
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE MGR=7839;


-- 8. WAQTD DNAME AND HIREDATE FOR EMPLOYEES HIRED AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT.
SELECT DNAME, HIREDATE
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE > '31-DEC-1983'
AND DNAME IN ('ACCOUNTING','RESEARCH');


-- 9. WAQTD ENAME AND DNAME OF THE EMPLOYEES WHO ARE GETTING COMM IN DEPT 10 OR 30.
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE COMM IS NOT NULL AND EMP.DEPTNO IN(10,30);


-- 10. WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHO'S EMPNO ARE (7839, 7902) AND ARE WORKING IN LOC NEW YORK.
SELECT DNAME, EMPNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMPNO IN (7839,7902) AND LOC IN ('NEW YORK');




-- ASSIGNMENT ON EMP AND MANAGER RELATION


-- 71.WAQTD SMITHS REPORTING MANAGER'S NAME.
SELECT ENAME
FROM EMP
WHERE EMPNO IN
(SELECT MGR
FROM EMP
WHERE ENAME='SMITH');


-- 72.WAQTD ADAMS MANAGER'S MANAGER NAME.
SELECT ENAME
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE ENAME='ADAMS'));


-- 73.WAQTD DNAME OF JONES MANAGER.
SELECT DNAME
FROM DEPT
WHERE DEPTNO =
(SELECT DEPTNO
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE ENAME='JONES'));


-- 74.WAQTD MILLER'S MANAGER'S SALARY.
SELECT SAL
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE ENAME='MILLER');


-- 75.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC
FROM DEPT
WHERE DEPTNO =
(SELECT DEPTNO
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE EMPNO =
(SELECT MGR
FROM EMP
WHERE ENAME='SMITH')));


-- 76.WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE.
SELECT ENAME
FROM EMP
WHERE MGR IN
(SELECT EMPNO
FROM EMP
WHERE ENAME='BLAKE');


-- 77.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING.
SELECT COUNT(*)
FROM EMP
WHERE MGR IN
(SELECT EMPNO
FROM EMP
WHERE ENAME='KING');


-- 78.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES.
SELECT *
FROM EMP
WHERE MGR IN
(SELECT EMPNO
FROM EMP
WHERE ENAME='JONES');


-- 79.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER.
SELECT ENAME
FROM EMP
WHERE MGR =
(SELECT MGR
FROM EMP
WHERE ENAME='BLAKE');


-- 80.WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER.
SELECT COUNT(*)
FROM EMP
WHERE MGR =
(SELECT MGR
FROM EMP
WHERE ENAME='FORD');