-- WAQTD ALL THE DETAILS FROM THE EMPLOYEE TABLE.
SELECT *
FROM EMP;

-- WAQTD NAMES OF ALL THE EMPLOYEES.
SELECT ENAME
FROM EMP;

-- WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME, SAL
FROM EMP;

-- WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME, COMM
FROM EMP;

-- WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES IN EMP TABLE.
SELECT EMPNO, DEPTNO
FROM EMP;

-- WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES.
SELECT ENAME, HIREDATE
FROM EMP;

-- WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES.
SELECT ENAME,JOB
FROM EMP;

-- WAQTD NAME, JOB AND SALARY GIVEN ALL THE EMPLOYEES.
SELECT ENAME,JOB,SAL
FROM EMP;

-- WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.
SELECT DNAME
FROM DEPT;

-- WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.
SELECT DNAME,LOC
FROM DEPT;

-- WAQTD ALL THE DETAILS ALONG WITH EMPLOYEE_NAME.
SELECT *
FROM EMP;

-- WAQTD ALL THE DETAILS ALONG WITH MANAGER, JOB, SALARY.
SELECT EMP.*, MGR,JOB,SAL
FROM EMP;

-- WAQTD ALL THE DETAILS ALONG WITH DEPARTMENT NAMES.
SELECT DEPT.*,DNAME
FROM DEPT;

-- WAQTD NAMES, MANAGER_ID, JOB AND COMMISION OF EMPLOYEES.
SELECT ENAME,MGR,JOB,COMM
FROM EMP;

-- WAQTD JOB, SALARY, COMMISION, NAMES OF EMPLOYEES.
SELECT JOB,SAL,COMM,ENAME
FROM EMP;
