======
-- SELF JOIN QUERIES 


-- 1. WAQTD EMPLOYEE NAME AND MANAGER NAME

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 2. WAQTD EMPLOYEE NAME AND MANAGER NAME IF EMPLOYEE SALARY > 3000

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.SAL > 3000;

-- 3. WAQTD EMPLOYEE NAME AND MANAGER NAME IF BOTH WORK IN SAME DEPARTMENT

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = E2.DEPTNO;

-- 4. WAQTD EMPLOYEE NAME AND MANAGER NAME IF EMPLOYEE HIRED AFTER 01-JAN-83

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.HIREDATE > '01-JAN-83';

-- 5. WAQTD EMPLOYEE NAME AND MANAGER NAME IF MANAGER SALARY > 4000

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E2.SAL > 4000;

-- 6. WAQTD EMPLOYEE NAME AND MANAGER NAME IF EMPLOYEE JOB IS CLERK

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.JOB = 'CLERK';

-- 7. WAQTD EMPLOYEE NAME AND MANAGER NAME IF EMPLOYEE SALARY < MANAGER SALARY

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.SAL < E2.SAL;

-- 8. WAQTD EMPLOYEE NAME AND MANAGER NAME IF BOTH BELONG TO DEPTNO 20

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = 20
AND E2.DEPTNO = 20;

-- 9. WAQTD EMPLOYEE NAME AND MANAGER NAME IF EMPLOYEE JOB IS ANALYST

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.JOB = 'ANALYST';

-- 10. WAQTD EMPLOYEE NAME AND MANAGER NAME IF MANAGER WORKS IN DEPTNO 10

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E2.DEPTNO = 10;

-- 11. WAQTD EMPLOYEE NAME AND THEIR MANAGER NAME

SELECT E1.ENAME EMPLOYEE, E2.ENAME MANAGER
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 12. WAQTD EMPLOYEES WHO EARN MORE THAN THEIR MANAGER

SELECT E1.ENAME, E2.ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.SAL > E2.SAL;

-- MULTIPLE JOIN QUERIES 


-- 13. WAQTD EMPLOYEE NAME, DEPARTMENT NAME AND LOCATION

SELECT E.ENAME, D.DNAME, D.LOC
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

-- 14. WAQTD EMPLOYEE NAME, MANAGER NAME AND DEPARTMENT NAME

SELECT E1.ENAME EMPLOYEE, E2.ENAME MANAGER, D.DNAME
FROM EMP E1
INNER JOIN EMP E2
ON E1.MGR = E2.EMPNO
INNER JOIN DEPT D
ON E1.DEPTNO = D.DEPTNO;

-- 15. WAQTD EMPLOYEE NAME, MANAGER NAME AND LOCATION

SELECT E1.ENAME EMPLOYEE, E2.ENAME MANAGER, D.LOC
FROM EMP E1
INNER JOIN EMP E2
ON E1.MGR = E2.EMPNO
INNER JOIN DEPT D
ON E1.DEPTNO = D.DEPTNO;

-- 16. WAQTD EMPLOYEE NAME, DEPARTMENT NAME AND MANAGER NAME

SELECT E1.ENAME, D.DNAME, E2.ENAME MANAGER
FROM EMP E1
INNER JOIN DEPT D
ON E1.DEPTNO = D.DEPTNO
INNER JOIN EMP E2
ON E1.MGR = E2.EMPNO;

-- 17. WAQTD EMPLOYEE NAME, SALARY, DEPARTMENT NAME AND LOCATION

SELECT E.ENAME, E.SAL, D.DNAME, D.LOC
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;
