-- ASSIGNMENT ON SUBQUERY CASE-1


-- 1. WAQTD ENAME OF THE EMPLOYEES EARNING MORE THAN ADAMS.
SELECT ENAME 
FROM EMP 
WHERE SAL > (SELECT SAL 
FROM EMP 
WHERE ENAME='ADAMS');

-- 2. WAQTD ENAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING.
SELECT ENAME,SAL  
FROM EMP 
WHERE SAL < (SELECT SAL 
FROM EMP 
WHERE ENAME='KING');

-- 3. WAQTD ENAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES.
SELECT ENAME, DEPTNO 
FROM EMP 
WHERE DEPTNO= (SELECT DEPTNO 
FROM EMP 
WHERE ENAME='JONES');

-- 4. WAQTD ENAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES.
SELECT ENAME,JOB 
FROM EMP 
WHERE JOB=(SELECT JOB 
FROM EMP 
WHERE ENAME='JAMES');

-- 5. WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARD’S ANNUAL SALARY.
SELECT EMPNO,ENAME,SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE SAL*12 >(SELECT SAL*12 
FROM EMP 
WHERE ENAME='WARD');

-- 6. WAQTD ENAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT.
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE 
FROM EMP 
WHERE ENAME='SCOTT');

-- 7. WAQTD ENAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED AFTER THE PRESIDENT.
SELECT ENAME,HIREDATE 
FROM EMP 
WHERE HIREDATE>(SELECT HIREDATE 
FROM EMP 
WHERE JOB='PRESIDENT');

-- 8. WAQTD ENAME AND SAL OF THE EMPLOYEES IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOSE EMPNO IS 7839.
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL<(SELECT SAL 
FROM EMP 
WHERE EMPNO=7839);

-- 9. WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER.
SELECT * 
FROM EMP 
WHERE HIREDATE<(SELECT HIREDATE 
FROM EMP 
WHERE ENAME='MILLER');

-- 10. WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN.
SELECT ENAME,EMPNO 
FROM EMP 
WHERE SAL>(SELECT SAL 
FROM EMP 
WHERE ENAME='ALLEN');

-- 11. WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL > (SELECT SAL 
FROM EMP  
WHERE ENAME='MILLER') 
AND SAL < (SELECT SAL 
FROM EMP 
WHERE ENAME='ALLEN');

-- 12. WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH.
SELECT * 
FROM EMP 
WHERE DEPTNO=20 AND JOB = (SELECT JOB 
FROM EMP 
WHERE ENAME='SMITH');

-- 13. WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER.
SELECT * 
FROM EMP 
WHERE JOB='MANAGER' 
AND DEPTNO =(SELECT DEPTNO 
FROM EMP 
WHERE ENAME='TURNER');

-- 14. WAQTD ENAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING.
SELECT ENAME,HIREDATE 
FROM EMP 
WHERE HIREDATE > '31-DEC-1980' 
AND HIREDATE < (SELECT HIREDATE 
FROM EMP  
WHERE ENAME='KING');

-- 15. WAQTD ENAME AND SAL ALONG WITH ANNUAL SAL FOR ALL EMPLOYEES WHOSE SAL IS LESS THAN BLAKE AND MORE THAN 3500.
SELECT ENAME,SAL , SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE SAL<(SELECT SAL 
FROM EMP 
WHERE ENAME='BLAKE') 
AND SAL>3500;

-- 16. WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING.
SELECT * 
FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SCOTT') 
AND SAL<(SELECT SAL FROM EMP WHERE ENAME='KING');

-- 17. WAQTD ENAME OF THE EMPLOYEES WHOSE NAME STARTS WITH ‘A’ AND WORKS IN THE SAME DEPT AS BLAKE.
SELECT ENAME 
FROM EMP 
WHERE ENAME LIKE 'A%' 
AND DEPTNO = (SELECT DEPTNO 
FROM EMP 
WHERE ENAME='BLAKE');

-- 18. WAQTD ENAME AND COMM IF EMPLOYEES EARN COMMISSION AND WORK IN THE SAME DESIGNATION AS SMITH.
SELECT ENAME, COMM 
FROM EMP 
WHERE COMM IS NOT NULL 
AND JOB = (SELECT JOB 
FROM EMP 
WHERE ENAME='SMITH');

-- 19. WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
SELECT * 
FROM EMP 
WHERE JOB='CLERK' 
AND DEPTNO = (SELECT DEPTNO 
FROM EMP 
WHERE ENAME='TURNER');

-- 20. WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.
SELECT ENAME, SAL, JOB 
FROM EMP 
WHERE SAL*12 > (SELECT SAL*12 
FROM EMP 
WHERE ENAME='SMITH') 
AND SAL*12 < (SELECT SAL*12 
FROM EMP 
WHERE ENAME='KING');

-- ASSIGNMENT ON SUBQUERY CASE – 1 & 2

-- 1. WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT.
SELECT ENAME 
FROM EMP 
WHERE SAL > (SELECT SAL 
FROM EMP 
WHERE ENAME='SCOTT') 
AND DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='ACCOUNTING');

-- 2. WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO.
SELECT * 
FROM EMP 
WHERE JOB='MANAGER' 
AND DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE LOC='CHICAGO');

-- 3. WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING.
SELECT ENAME,SAL 
FROM EMP 
WHERE SAL>(SELECT SAL 
FROM EMP 
WHERE ENAME='KING') 
AND DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='ACCOUNTING');

-- 4. WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTMENT SALES.
SELECT * 
FROM EMP 
WHERE JOB='SALESMAN' 
AND DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='SALES');

-- 5. WAQTD NAME, SAL, JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING.
SELECT ENAME,SAL,JOB,HIREDATE 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='OPERATIONS') 
AND HIREDATE<(SELECT HIREDATE 
FROM EMP 
WHERE ENAME='KING');

-- 6. DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMENT NAME ENDING 'S'.
SELECT * 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME LIKE '%S');

-- 7. WAQTD DNAME OF THE EMPLOYEES WHOSE NAMES HAS CHARACTER ‘A’ IN IT.
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE ENAME LIKE '%A%');

-- 8. WAQTD DNAME AND LOC OF THE EMPLOYEES WHOSE SALARY IS RUPEES 800.
SELECT DNAME,LOC 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE SAL=800);

-- 9. WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION.
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE COMM IS NOT NULL);

-- 10. WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40.
SELECT LOC 
FROM DEPT 
WHERE DEPTNO=40 
AND DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE COMM IS NOT NULL);


-- ASSIGNMENT ON SUBQUERY CASE-2

-- 1. WAQTD DNAME OF THE EMPLOYEES WHOSE NAME IS SMITH.
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE ENAME='SMITH');

-- 2. WAQTD DNAME AND LOC OF THE EMPLOYEE WHOSE ENAME IS KING.
SELECT DNAME,LOC 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE ENAME='KING');

-- 3. WAQTD LOC OF THE EMP WHOSE EMPLOYEE NUMBER IS 7902.
SELECT LOC 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE EMPNO=7902);

-- 4. WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOSE NAME ENDS WITH ‘R’.
SELECT DNAME,LOC,DEPTNO 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE ENAME LIKE '%R');

-- 5. WAQTD DNAME OF THE EMPLOYEE WHOSE DESIGNATION IS PRESIDENT.
SELECT DNAME 
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM EMP 
WHERE JOB='PRESIDENT');

-- 6. WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT.
SELECT ENAME 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='ACCOUNTING');

-- 7. WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION ‘CHICAGO’.
SELECT ENAME,SAL 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE LOC='CHICAGO');

-- 8. WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES.
SELECT * 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='SALES');

-- 9. WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK.
SELECT EMP.*, SAL*12 AS ANNUAL_SAL 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE LOC='NEW YORK');

-- 10. WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT.
SELECT ENAME 
FROM EMP 
WHERE DEPTNO IN(SELECT DEPTNO 
FROM DEPT 
WHERE DNAME='OPERATIONS');